Utopszkij_fw: PHPMailer Class Reference
PHPMailer Class Reference
Public Member Functions
__construct ($exceptions=null)
__destruct ()
isHTML ($isHtml=true)
isSMTP ()
isMail ()
isSendmail ()
isQmail ()
addAddress ($address, $name='')
addCC ($address, $name='')
addBCC ($address, $name='')
addReplyTo ($address, $name='')
setBoundaries ()
setFrom ($address, $name='', $auto=true)
getLastMessageID ()
punyencodeAddress ($address)
send ()
preSend ()
postSend ()
getSMTPInstance ()
setSMTPInstance (SMTP $smtp)
smtpConnect ($options=null)
smtpClose ()
setLanguage ($langcode='en', $lang_path='')
getTranslations ()
addrAppend ($type, $addr)
addrFormat ($addr)
wrapText ($message, $length, $qp_mode=false)
utf8CharBoundary ($encodedText, $maxLength)
setWordWrap ()
createHeader ()
getMailMIME ()
getSentMIMEMessage ()
createBody ()
getBoundaries ()
headerLine ($name, $value)
textLine ($value)
addAttachment ($path, $name='', $encoding=self::ENCODING_BASE64, $type='', $disposition='attachment')
getAttachments ()
encodeString ($str, $encoding=self::ENCODING_BASE64)
encodeHeader ($str, $position='text')
hasMultiBytes ($str)
has8bitChars ($text)
base64EncodeWrapMB ($str, $linebreak=null)
encodeQP ($string)
encodeQ ($str, $position='text')
addStringAttachment ($string, $filename, $encoding=self::ENCODING_BASE64, $type='', $disposition='attachment')
addEmbeddedImage ($path, $cid, $name='', $encoding=self::ENCODING_BASE64, $type='', $disposition='inline')
addStringEmbeddedImage ($string, $cid, $name='', $encoding=self::ENCODING_BASE64, $type='', $disposition='inline')
inlineImageExists ()
attachmentExists ()
alternativeExists ()
clearQueuedAddresses ($kind)
clearAddresses ()
clearCCs ()
clearBCCs ()
clearReplyTos ()
clearAllRecipients ()
clearAttachments ()
clearCustomHeaders ()
isError ()
addCustomHeader ($name, $value=null)
getCustomHeaders ()
msgHTML ($message, $basedir='', $advanced=false)
html2text ($html, $advanced=false)
set ($name, $value='')
secureHeader ($str)
sign ($cert_filename, $key_filename, $key_pass, $extracerts_filename='')
DKIM_QP ($txt)
DKIM_Sign ($signHeader)
DKIM_HeaderC ($signHeader)
DKIM_BodyC ($body)
DKIM_Add ($headers_line, $subject, $body)
getToAddresses ()
getCcAddresses ()
getBccAddresses ()
getReplyToAddresses ()
getAllRecipientAddresses ()
getOAuth ()
setOAuth (OAuthTokenProvider $oauth)
Static Public Member Functions
static parseAddresses ($addrstr, $useimap=true, $charset=self::CHARSET_ISO88591)
static validateAddress ($address, $patternselect=null)
static idnSupported ()
static rfcDate ()
static isValidHost ($host)
static _mime_types ($ext='')
static filenameToType ($filename)
static mb_pathinfo ($path, $options=null)
static normalizeBreaks ($text, $breaktype=null)
static stripTrailingWSP ($text)
static stripTrailingBreaks ($text)
static getLE ()
static hasLineLongerThanMax ($str)
static quotedString ($str)
Public Attributes
const CHARSET_ASCII = 'us-ascii'
const CHARSET_ISO88591 = 'iso-8859-1'
const CHARSET_UTF8 = 'utf-8'
const CONTENT_TYPE_PLAINTEXT = 'text/plain'
const CONTENT_TYPE_TEXT_CALENDAR = 'text/calendar'
const CONTENT_TYPE_TEXT_HTML = 'text/html'
const CONTENT_TYPE_MULTIPART_ALTERNATIVE = 'multipart/alternative'
const CONTENT_TYPE_MULTIPART_MIXED = 'multipart/mixed'
const CONTENT_TYPE_MULTIPART_RELATED = 'multipart/related'
const ENCODING_7BIT = '7bit'
const ENCODING_8BIT = '8bit'
const ENCODING_BASE64 = 'base64'
const ENCODING_BINARY = 'binary'
const ENCODING_QUOTED_PRINTABLE = 'quoted-printable'
const ENCRYPTION_STARTTLS = 'tls'
const ENCRYPTION_SMTPS = 'ssl'
const ICAL_METHOD_REQUEST = 'REQUEST'
const ICAL_METHOD_PUBLISH = 'PUBLISH'
const ICAL_METHOD_REPLY = 'REPLY'
const ICAL_METHOD_ADD = 'ADD'
const ICAL_METHOD_CANCEL = 'CANCEL'
const ICAL_METHOD_REFRESH = 'REFRESH'
const ICAL_METHOD_COUNTER = 'COUNTER'
const ICAL_METHOD_DECLINECOUNTER = 'DECLINECOUNTER'
$Priority
$CharSet = self::CHARSET_ISO88591
$ContentType = self::CONTENT_TYPE_PLAINTEXT
$Encoding = self::ENCODING_8BIT
$ErrorInfo = ''
$From = ''
$FromName = ''
$Sender = ''
$Subject = ''
$Body = ''
$AltBody = ''
$Ical = ''
$WordWrap = 0
$Mailer = 'mail'
$Sendmail = '/usr/sbin/sendmail'
$UseSendmailOptions = true
$ConfirmReadingTo = ''
$Hostname = ''
$MessageID = ''
$MessageDate = ''
$Host = 'localhost'
$Port = 25
$Helo = ''
$SMTPSecure = ''
$SMTPAutoTLS = true
$SMTPAuth = false
$SMTPOptions = []
$Username = ''
$Password = ''
$AuthType = ''
$Timeout = 300
$dsn = ''
$SMTPDebug = 0
$Debugoutput = 'echo'
$SMTPKeepAlive = false
$SingleTo = false
$do_verp = false
$AllowEmpty = false
$DKIM_selector = ''
$DKIM_identity = ''
$DKIM_passphrase = ''
$DKIM_domain = ''
$DKIM_copyHeaderFields = true
$DKIM_extraHeaders = []
$DKIM_private = ''
$DKIM_private_string = ''
$action_function = ''
$XMailer = ''
const VERSION = '6.7.1'
const STOP_MESSAGE = 0
const STOP_CONTINUE = 1
const STOP_CRITICAL = 2
const CRLF = "\r\n"
const FWS = ' '
const MAIL_MAX_LINE_LENGTH = 63
const MAX_LINE_LENGTH = 998
const STD_LINE_LENGTH = 76
Static Public Attributes
static $validator = 'php'
Protected Member Functions
edebug ($str)
addOrEnqueueAnAddress ($kind, $address, $name)
addAnAddress ($kind, $address, $name='')
sendmailSend ($header, $body)
mailSend ($header, $body)
smtpSend ($header, $body)
generateId ()
getBoundary ($boundary, $charSet, $contentType, $encoding)
endBoundary ($boundary)
setMessageType ()
attachAll ($disposition_type, $boundary)
encodeFile ($path, $encoding=self::ENCODING_BASE64)
validateEncoding ($encoding)
cidExists ($cid)
setError ($msg)
serverHostname ()
lang ($key)
doCallback ($isSent, $to, $cc, $bcc, $subject, $body, $from, $extra)
Static Protected Member Functions
static isShellSafe ($string)
static isPermittedPath ($path)
static fileIsAccessible ($path)
static setLE ($le)
Protected Attributes
$MIMEBody = ''
$MIMEHeader = ''
$mailHeader = ''
$oauth
$SingleToArray = []
$smtp
$to = []
$cc = []
$bcc = []
$ReplyTo = []
$all_recipients = []
$RecipientsQueue = []
$ReplyToQueue = []
$attachment = []
$CustomHeader = []
$lastMessageID = ''
$message_type = ''
$boundary = []
$language = []
$error_count = 0
$sign_cert_file = ''
$sign_key_file = ''
$sign_extracerts_file = ''
$sign_key_pass = ''
$exceptions = false
$uniqueid = ''
Static Protected Attributes
static $IcalMethods
static $LE = self::CRLF
Detailed Description
PHPMailer - PHP email creation and transport class.
Author
Marcus Bointon (Synchro/coolbru) phpma.nosp@m.iler.nosp@m.@sync.nosp@m.hrom.nosp@m.edia..nosp@m.co.u.nosp@m.k
Jim Jagielski (jimjag) jimja.nosp@m.g@gm.nosp@m.ail.c.nosp@m.om
Andy Prevost (codeworxtech) codew.nosp@m.orxt.nosp@m.ech@u.nosp@m.sers.nosp@m..sour.nosp@m.cefo.nosp@m.rge.n.nosp@m.et
Brent R. Matzelle (original founder)
Constructor & Destructor Documentation
__construct()
__construct ($exceptions = null)
Constructor.
Parameters
bool $exceptions Should we throw external exceptions?
__destruct()
__destruct ()
Destructor.
Member Function Documentation
_mime_types()
static _mime_types ($ext = '') static
Get the MIME type for a file extension.
Parameters
string $ext File extension
Returns
string MIME type of file
addAddress()
addAddress ($address, $name = '')
Add a "To" address.
Parameters
string $address The email address to send to
string $name
Exceptions
Exception
Returns
bool true on success, false if address already used or invalid in some way
addAnAddress()
addAnAddress ($kind, $address, $name = '') protected
Add an address to one of the recipient arrays or to the ReplyTo array. Addresses that have been added already return false, but do not throw exceptions.
Parameters
string $kind One of 'to', 'cc', 'bcc', or 'ReplyTo'
string $address The email address to send, resp. to reply to
string $name
Exceptions
Exception
Returns
bool true on success, false if address already used or invalid in some way
addAttachment()
addAttachment ($path, $name = '', $encoding = self::ENCODING_BASE64, $type = '', $disposition = 'attachment')
Add an attachment from a path on the filesystem. Never use a user-supplied path to a file! Returns false if the file could not be found or read. Explicitly does not support passing URLs; PHPMailer is not an HTTP client. If you need to do that, fetch the resource yourself and pass it in via a local file or string.
Parameters
string $path Path to the attachment
string $name Overrides the attachment name
string $encoding File encoding (see $Encoding)
string $type MIME type, e.g. image/jpeg; determined automatically from $path if not specified
string $disposition Disposition to use
Exceptions
Exception
Returns
bool
addBCC()
addBCC ($address, $name = '')
Add a "BCC" address.
Parameters
string $address The email address to send to
string $name
Exceptions
Exception
Returns
bool true on success, false if address already used or invalid in some way
addCC()
addCC ($address, $name = '')
Add a "CC" address.
Parameters
string $address The email address to send to
string $name
Exceptions
Exception
Returns
bool true on success, false if address already used or invalid in some way
addCustomHeader()
addCustomHeader ($name, $value = null)
Add a custom header. $name value can be overloaded to contain both header name and value (name:value).
Parameters
string $name Custom header name
string | null $value Header value
Returns
bool True if a header was set successfully
Exceptions
Exception
addEmbeddedImage()
addEmbeddedImage ($path, $cid, $name = '', $encoding = self::ENCODING_BASE64, $type = '', $disposition = 'inline')
Add an embedded (inline) attachment from a file. This can include images, sounds, and just about any other document type. These differ from 'regular' attachments in that they are intended to be displayed inline with the message, not just attached for download. This is used in HTML messages that embed the images the HTML refers to using the $cid value in img tags, for example <img src="cid:mylogo">. Never use a user-supplied path to a file!
Parameters
string $path Path to the attachment
string $cid Content ID of the attachment; Use this to reference the content when using an embedded image in HTML
string $name Overrides the attachment filename
string $encoding File encoding (see $Encoding) defaults to base64
string $type File MIME type (by default mapped from the $path filename's extension)
string $disposition Disposition to use: inline (default) or attachment (unlikely you want this {
See also
addAttachment()} instead)
Returns
bool True on successfully adding an attachment
Exceptions
Exception
Referenced by PHPMailer\msgHTML().
addOrEnqueueAnAddress()
addOrEnqueueAnAddress ($kind, $address, $name) protected
Add an address to one of the recipient arrays or to the ReplyTo array. Because PHPMailer can't validate addresses with an IDN without knowing the PHPMailer::$CharSet (that can still be modified after calling this function), addition of such addresses is delayed until send(). Addresses that have been added already return false, but do not throw exceptions.
Parameters
string $kind One of 'to', 'cc', 'bcc', or 'ReplyTo'
string $address The email address
string $name An optional username associated with the address
Exceptions
Exception
Returns
bool true on success, false if address already used or invalid in some way
Referenced by PHPMailer\addAddress(), PHPMailer\addBCC(), PHPMailer\addCC(), and PHPMailer\addReplyTo().
addrAppend()
addrAppend ($type, $addr)
Create recipient headers.
Parameters
string $type
array $addr An array of recipients, where each recipient is a 2-element indexed array with element 0 containing an address and element 1 containing a name, like: [['joe@e.nosp@m.xamp.nosp@m.le.co.nosp@m.m', 'Joe User'], ['zoe@e.nosp@m.xamp.nosp@m.le.co.nosp@m.m', 'Zoe User']]
Returns
string
Referenced by PHPMailer\createHeader().
addReplyTo()
addReplyTo ($address, $name = '')
Add a "Reply-To" address.
Parameters
string $address The email address to reply to
string $name
Exceptions
Exception
Returns
bool true on success, false if address already used or invalid in some way
addrFormat()
addrFormat ($addr)
Format an address for use in a message header.
Parameters
array $addr A 2-element indexed array, element 0 containing an address, element 1 containing a name like ['joe@e.nosp@m.xamp.nosp@m.le.co.nosp@m.m', 'Joe User']
Returns
string
Referenced by PHPMailer\addrAppend(), PHPMailer\createHeader(), and PHPMailer\mailSend().
addStringAttachment()
addStringAttachment ($string, $filename, $encoding = self::ENCODING_BASE64, $type = '', $disposition = 'attachment')
Add a string or binary attachment (non-filesystem). This method can be used to attach ascii or binary data, such as a BLOB record from a database.
Parameters
string $string String attachment data
string $filename Name of the attachment
string $encoding File encoding (see $Encoding)
string $type File extension (MIME) type
string $disposition Disposition to use
Exceptions
Exception
Returns
bool True on successfully adding an attachment
addStringEmbeddedImage()
addStringEmbeddedImage ($string, $cid, $name = '', $encoding = self::ENCODING_BASE64, $type = '', $disposition = 'inline')
Add an embedded stringified attachment. This can include images, sounds, and just about any other document type. If your filename doesn't contain an extension, be sure to set the $type to an appropriate MIME type.
Parameters
string $string The attachment binary data
string $cid Content ID of the attachment; Use this to reference the content when using an embedded image in HTML
string $name A filename for the attachment. If this contains an extension, PHPMailer will attempt to set a MIME type for the attachment. For example 'file.jpg' would get an 'image/jpeg' MIME type.
string $encoding File encoding (see $Encoding), defaults to 'base64'
string $type MIME type - will be used in preference to any automatically derived type
string $disposition Disposition to use
Exceptions
Exception
Returns
bool True on successfully adding an attachment
Referenced by PHPMailer\msgHTML().
alternativeExists()
alternativeExists ()
Check if this message has an alternative body set.
Returns
bool
Referenced by PHPMailer\msgHTML(), and PHPMailer\setMessageType().
attachAll()
attachAll ($disposition_type, $boundary) protected
Attach all file, string, and binary attachments to the message. Returns an empty string on failure.
Parameters
string $disposition_type
string $boundary
Exceptions
Exception
Returns
string
Referenced by PHPMailer\createBody().
attachmentExists()
attachmentExists ()
Check if an attachment (non-inline) is present.
Returns
bool
Referenced by PHPMailer\setMessageType().
base64EncodeWrapMB()
base64EncodeWrapMB ($str, $linebreak = null)
Encode and wrap long multibyte strings for mail headers without breaking lines within a character. Adapted from a function by paravoid.
See also
http://www.php.net/manual/en/function.mb-encode-mimeheader.php#60283
Parameters
string $str multi-byte text to wrap encode
string $linebreak string to use as linefeed/end-of-line
Returns
string
Referenced by PHPMailer\encodeHeader().
cidExists()
cidExists ($cid) protected
Check if an embedded attachment is present with this cid.
Parameters
string $cid
Returns
bool
Referenced by PHPMailer\msgHTML().
clearAddresses()
clearAddresses ()
Clear all To recipients.
clearAllRecipients()
clearAllRecipients ()
Clear all recipient types.
clearAttachments()
clearAttachments ()
Clear all filesystem, string, and binary attachments.
clearBCCs()
clearBCCs ()
Clear all BCC recipients.
clearCCs()
clearCCs ()
Clear all CC recipients.
clearCustomHeaders()
clearCustomHeaders ()
Clear all custom headers.
clearQueuedAddresses()
clearQueuedAddresses ($kind)
Clear queued addresses of given kind.
Parameters
string $kind 'to', 'cc', or 'bcc'
Referenced by PHPMailer\clearAddresses(), PHPMailer\clearBCCs(), and PHPMailer\clearCCs().
clearReplyTos()
clearReplyTos ()
Clear all ReplyTo recipients.
createBody()
createBody ()
Assemble the message body. Returns an empty string on failure.
Exceptions
Exception
Returns
string The assembled message body
createHeader()
createHeader ()
Assemble message headers.
Returns
string The assembled headers
DKIM_Add()
DKIM_Add ($headers_line, $subject, $body)
Create the DKIM header and body in a new message header.
Parameters
string $headers_line Header lines
string $subject Subject
string $body Body
Exceptions
Exception
Returns
string
DKIM_BodyC()
DKIM_BodyC ($body)
Generate a DKIM canonicalization body. Uses the 'simple' algorithm from RFC6376 section 3.4.3. Canonicalized bodies should always use CRLF, regardless of mailer setting.
See also
https://tools.ietf.org/html/rfc6376#section-3.4.3
Parameters
string $body Message Body
Returns
string
Referenced by PHPMailer\DKIM_Add().
DKIM_HeaderC()
DKIM_HeaderC ($signHeader)
Generate a DKIM canonicalization header. Uses the 'relaxed' algorithm from RFC6376 section 3.4.2. Canonicalized headers should always use CRLF, regardless of mailer setting.
See also
https://tools.ietf.org/html/rfc6376#section-3.4.2
Parameters
string $signHeader Header
Returns
string
Referenced by PHPMailer\DKIM_Add().
DKIM_QP()
DKIM_QP ($txt)
Quoted-Printable-encode a DKIM header.
Parameters
string $txt
Returns
string
Referenced by PHPMailer\DKIM_Add().
DKIM_Sign()
DKIM_Sign ($signHeader)
Generate a DKIM signature.
Parameters
string $signHeader
Exceptions
Exception
Returns
string The DKIM signature value
Referenced by PHPMailer\DKIM_Add().
doCallback()
doCallback ($isSent, $to, $cc, $bcc, $subject, $body, $from, $extra) protected
Perform a callback.
Parameters
bool $isSent
array $to
array $cc
array $bcc
string $subject
string $body
string $from
array $extra
Referenced by PHPMailer\mailSend(), and PHPMailer\smtpSend().
edebug()
edebug ($str) protected
Output debugging info via a user-defined method. Only generates output if debug output is enabled.
See also
PHPMailer::$Debugoutput
PHPMailer::$SMTPDebug
Parameters
string $str
@noinspection ForgottenDebugOutputInspection
Referenced by PHPMailer\addAnAddress(), PHPMailer\addAttachment(), PHPMailer\addEmbeddedImage(), PHPMailer\addOrEnqueueAnAddress(), PHPMailer\addStringAttachment(), PHPMailer\addStringEmbeddedImage(), PHPMailer\encodeFile(), and PHPMailer\smtpConnect().
encodeFile()
encodeFile ($path, $encoding = self::ENCODING_BASE64) protected
Encode a file attachment in requested format. Returns an empty string on failure.
Parameters
string $path The full path to the file
string $encoding The encoding to use; one of 'base64', '7bit', '8bit', 'binary', 'quoted-printable'
Returns
string
Referenced by PHPMailer\attachAll().
encodeHeader()
encodeHeader ($str, $position = 'text')
Encode a header value (not including its label) optimally. Picks shortest of Q, B, or none. Result includes folding if needed. See RFC822 definitions for phrase, comment and text positions.
Parameters
string $str The header value to encode
string $position What context the string will be used in
Returns
string
Referenced by PHPMailer\addrFormat(), PHPMailer\attachAll(), and PHPMailer\createHeader().
encodeQ()
encodeQ ($str, $position = 'text')
Encode a string using Q encoding.
See also
http://tools.ietf.org/html/rfc2047#section-4.2
Parameters
string $str the text to encode
string $position Where the text is going to be used, see the RFC for what that means
Returns
string
Referenced by PHPMailer\encodeHeader().
encodeQP()
encodeQP ($string)
Encode a string in quoted-printable format. According to RFC2045 section 6.7.
Parameters
string $string The text to encode
Returns
string
Referenced by PHPMailer\encodeString().
encodeString()
encodeString ($str, $encoding = self::ENCODING_BASE64)
Encode a string in requested format. Returns an empty string on failure.
Parameters
string $str The text to encode
string $encoding The encoding to use; one of 'base64', '7bit', '8bit', 'binary', 'quoted-printable'
Exceptions
Exception
Returns
string
Referenced by PHPMailer\attachAll(), PHPMailer\createBody(), and PHPMailer\encodeFile().
endBoundary()
endBoundary ($boundary) protected
Return the end of a message boundary.
Parameters
string $boundary
Returns
string
Referenced by PHPMailer\createBody().
fileIsAccessible()
static fileIsAccessible ($path) static protected
Check whether a file path is safe, accessible, and readable.
Parameters
string $path A relative or absolute path to a file
Returns
bool
filenameToType()
static filenameToType ($filename) static
Map a file name to a MIME type. Defaults to 'application/octet-stream', i.e.. arbitrary binary data.
Parameters
string $filename A file name or full path, does not need to exist as a file
Returns
string
generateId()
generateId () protected
Create a unique ID to use for boundaries.
Returns
string
@noinspection CryptographicallySecureRandomnessInspection
Referenced by PHPMailer\setBoundaries().
getAllRecipientAddresses()
getAllRecipientAddresses ()
Allows for public read access to 'all_recipients' property. Before the send() call, queued addresses (i.e. with IDN) are not yet included.
Returns
array
getAttachments()
getAttachments ()
Return the array of attachments.
Returns
array
getBccAddresses()
getBccAddresses ()
Allows for public read access to 'bcc' property. Before the send() call, queued addresses (i.e. with IDN) are not yet included.
Returns
array
getBoundaries()
getBoundaries ()
Get the boundaries that this message will use
Returns
array
getBoundary()
getBoundary ($boundary, $charSet, $contentType, $encoding) protected
Return the start of a message boundary.
Parameters
string $boundary
string $charSet
string $contentType
string $encoding
Returns
string
Referenced by PHPMailer\createBody().
getCcAddresses()
getCcAddresses ()
Allows for public read access to 'cc' property. Before the send() call, queued addresses (i.e. with IDN) are not yet included.
Returns
array
getCustomHeaders()
getCustomHeaders ()
Returns all custom headers.
Returns
array
getLastMessageID()
getLastMessageID ()
Return the Message-ID header of the last email. Technically this is the value from the last time the headers were created, but it's also the message ID of the last sent message except in pathological cases.
Returns
string
getLE()
static getLE () static
Return the current line break format string.
Returns
string
getMailMIME()
getMailMIME ()
Get the message MIME type headers.
Returns
string
Referenced by PHPMailer\createBody(), and PHPMailer\createHeader().
getOAuth()
getOAuth ()
Get the OAuthTokenProvider instance.
Returns
OAuthTokenProvider
getReplyToAddresses()
getReplyToAddresses ()
Allows for public read access to 'ReplyTo' property. Before the send() call, queued addresses (i.e. with IDN) are not yet included.
Returns
array
getSentMIMEMessage()
getSentMIMEMessage ()
Returns the whole MIME message. Includes complete headers and body. Only valid post preSend().
See also
PHPMailer::preSend()
Returns
string
getSMTPInstance()
getSMTPInstance ()
Get an instance to use for SMTP operations. Override this function to load your own SMTP implementation, or set one with setSMTPInstance.
Returns
SMTP
Referenced by PHPMailer\smtpConnect().
getToAddresses()
getToAddresses ()
Allows for public read access to 'to' property. Before the send() call, queued addresses (i.e. with IDN) are not yet included.
Returns
array
getTranslations()
getTranslations ()
Get the array of strings for the current language.
Returns
array
has8bitChars()
has8bitChars ($text)
Does a string contain any 8-bit chars (in any charset)?
Parameters
string $text
Returns
bool
Referenced by PHPMailer\addOrEnqueueAnAddress(), PHPMailer\createBody(), and PHPMailer\encodeHeader().
hasLineLongerThanMax()
static hasLineLongerThanMax ($str) static
Detect if a string contains a line longer than the maximum line length allowed by RFC 2822 section 2.1.1.
Parameters
string $str
Returns
bool
hasMultiBytes()
hasMultiBytes ($str)
Check if a string contains multi-byte characters.
Parameters
string $str multi-byte text to wrap encode
Returns
bool
Referenced by PHPMailer\encodeHeader().
headerLine()
headerLine ($name, $value)
Format a header line.
Parameters
string $name
string | int $value
Returns
string
Referenced by PHPMailer\createBody(), PHPMailer\createHeader(), PHPMailer\getBoundary(), and PHPMailer\getMailMIME().
html2text()
html2text ($html, $advanced = false)
Convert an HTML string into plain text. This is used by msgHTML(). Note - older versions of this function used a bundled advanced converter which was removed for license reasons in #232. Example usage:
//Use default conversion
$plain = $mail->html2text($html);
//Use your own custom converter
$plain = $mail->html2text($html, function($html) {
    $converter = new MyHtml2text($html);
    return $converter->get_text();
});
Parameters
string $html The HTML text to convert
bool | callable $advanced Any boolean value to use the internal converter, or provide your own callable for custom conversion. Never pass user-supplied data into this parameter
Returns
string
Referenced by PHPMailer\msgHTML().
idnSupported()
static idnSupported () static
Tells whether IDNs (Internationalized Domain Names) are supported or not. This requires the intl and mbstring PHP extensions.
Returns
bool true if required functions for IDN support are present
inlineImageExists()
inlineImageExists ()
Check if an inline attachment is present.
Returns
bool
Referenced by PHPMailer\setMessageType().
isError()
isError ()
Check if an error occurred.
Returns
bool True if an error did occur
Referenced by PHPMailer\attachAll(), and PHPMailer\createBody().
isHTML()
isHTML ($isHtml = true)
Sets message type to HTML or plain.
Parameters
bool $isHtml True for HTML mode
Referenced by PHPMailer\msgHTML().
isMail()
isMail ()
Send messages using PHP's mail() function.
isPermittedPath()
static isPermittedPath ($path) static protected
Check whether a file path is of a permitted type. Used to reject URLs and phar files from functions that access local file paths, such as addAttachment.
Parameters
string $path A relative or absolute path to a file
Returns
bool
isQmail()
isQmail ()
Send messages using qmail.
isSendmail()
isSendmail ()
Send messages using $Sendmail.
isShellSafe()
static isShellSafe ($string) static protected
Fix CVE-2016-10033 and CVE-2016-10045 by disallowing potentially unsafe shell characters. Note that escapeshellarg and escapeshellcmd are inadequate for our purposes, especially on Windows.
See also
https://github.com/PHPMailer/PHPMailer/issues/924 CVE-2016-10045 bug report
Parameters
string $string The string to be validated
Returns
bool
isSMTP()
isSMTP ()
Send messages using SMTP.
isValidHost()
static isValidHost ($host) static
Validate whether a string contains a valid value to use as a hostname or IP address. IPv6 addresses must include [], e.g. [::1], not just ::1.
Parameters
string $host The host name or IP address to check
Returns
bool
lang()
lang ($key) protected
Get an error message in the current language.
Parameters
string $key
Returns
string
Referenced by PHPMailer\addAnAddress(), PHPMailer\addAttachment(), PHPMailer\addCustomHeader(), PHPMailer\addEmbeddedImage(), PHPMailer\addOrEnqueueAnAddress(), PHPMailer\addStringAttachment(), PHPMailer\addStringEmbeddedImage(), PHPMailer\createBody(), PHPMailer\DKIM_Sign(), PHPMailer\encodeFile(), PHPMailer\encodeString(), PHPMailer\mailSend(), PHPMailer\set(), PHPMailer\setError(), PHPMailer\smtpConnect(), and PHPMailer\smtpSend().
mailSend()
mailSend ($header, $body) protected
Send mail using the PHP mail() function.
See also
http://www.php.net/manual/en/book.mail.php
Parameters
string $header The message headers
string $body The message body
Exceptions
Exception
Returns
bool
mb_pathinfo()
static mb_pathinfo ($path, $options = null) static
Multi-byte-safe pathinfo replacement. Drop-in replacement for pathinfo(), but multibyte- and cross-platform-safe.
See also
http://www.php.net/manual/en/function.pathinfo.php#107461
Parameters
string $path A filename or path, does not need to exist as a file
int | string $options Either a PATHINFO_* constant, or a string name to return only the specified piece
Returns
string|array
msgHTML()
msgHTML ($message, $basedir = '', $advanced = false)
Create a message body from an HTML string. Automatically inlines images and creates a plain-text version by converting the HTML, overwriting any existing values in Body and AltBody. Do not source $message content from user input! $basedir is prepended when handling relative URLs, e.g. and must not be empty will look for an image file in $basedir/images/a.png and convert it to inline. If you don't provide a $basedir, relative paths will be left untouched (and thus probably break in email) Converts data-uri images into embedded attachments. If you don't want to apply these transformations to your HTML, just set Body and AltBody directly.
Parameters
string $message HTML message string
string $basedir Absolute path to a base directory to prepend to relative paths to images
bool | callable $advanced Whether to use the internal HTML to text converter or your own custom converter
Returns
string The transformed message body
Exceptions
Exception
See also
PHPMailer::html2text()
normalizeBreaks()
static normalizeBreaks ($text, $breaktype = null) static
Normalize line breaks in a string. Converts UNIX LF, Mac CR and Windows CRLF line breaks into a single line break format. Defaults to CRLF (for message bodies) and preserves consecutive breaks.
Parameters
string $text
string $breaktype What kind of line break to use; defaults to static::$LE
Returns
string
parseAddresses()
static parseAddresses ($addrstr, $useimap = true, $charset = self::CHARSET_ISO88591) static
Parse and validate a string containing one or more RFC822-style comma-separated email addresses of the form "display name <address>" into an array of name/address pairs. Uses the imap_rfc822_parse_adrlist function if the IMAP extension is available. Note that quotes in the name part are removed.
See also
http://www.andrew.cmu.edu/user/agreen1/testing/mrbs/web/Mail/RFC822.php A more careful implementation
Parameters
string $addrstr The address list string
bool $useimap Whether to use the IMAP extension to parse the list
string $charset The charset to use when decoding the address list string.
Returns
array
postSend()
postSend ()
Actually send a message via the selected mechanism.
Exceptions
Exception
Returns
bool
preSend()
preSend ()
Prepare a message for sending.
Exceptions
Exception
Returns
bool
punyencodeAddress()
punyencodeAddress ($address)
Converts IDN in given email address to its ASCII form, also known as punycode, if possible. Important: Address must be passed in same encoding as currently set in PHPMailer::$CharSet. This function silently returns unmodified address if:
No conversion is necessary (i.e. domain name is not an IDN, or is already in ASCII form)
Conversion to punycode is impossible (e.g. required PHP functions are not available) or fails for any reason (e.g. domain contains characters not allowed in an IDN).
See also
PHPMailer::$CharSet
Parameters
string $address The email address to convert
Returns
string The encoded address in ASCII form
quotedString()
static quotedString ($str) static
If a string contains any "special" characters, double-quote the name, and escape any double quotes with a backslash.
Parameters
string $str
Returns
string
See also
RFC822 3.4.1
rfcDate()
static rfcDate () static
Return an RFC 822 formatted date.
Returns
string
secureHeader()
secureHeader ($str)
Strip newlines to prevent header injection.
Parameters
string $str
Returns
string
Referenced by PHPMailer\addrFormat(), PHPMailer\attachAll(), and PHPMailer\createHeader().
send()
send ()
Create a message and send it. Uses the sending method specified by $Mailer.
Exceptions
Exception
Returns
bool false on error - See the ErrorInfo property for details of the error
sendmailSend()
sendmailSend ($header, $body) protected
Send mail using the $Sendmail program.
See also
PHPMailer::$Sendmail
Parameters
string $header The message headers
string $body The message body
Exceptions
Exception
Returns
bool
serverHostname()
serverHostname () protected
Get the server hostname. Returns 'localhost.localdomain' if unknown.
Returns
string
Referenced by PHPMailer\createHeader(), and PHPMailer\smtpConnect().
set()
set ($name, $value = '')
Set or reset instance properties. You should avoid this function - it's more verbose, less efficient, more error-prone and harder to debug than setting properties directly. Usage Example: ‘$mail->set('SMTPSecure’, static::ENCRYPTION_STARTTLS);` is the same as: $mail->SMTPSecure = static::ENCRYPTION_STARTTLS;.
Parameters
string $name The property name to set
mixed $value The value to set the property to
Returns
bool
setBoundaries()
setBoundaries ()
Set the boundaries to use for delimiting MIME parts. If you override this, ensure you set all 3 boundaries to unique values. The default boundaries include a "=_" sequence which cannot occur in quoted-printable bodies, as suggested by https://www.rfc-editor.org/rfc/rfc2045#section-6.7
Returns
void
Referenced by PHPMailer\createBody(), and PHPMailer\getBoundaries().
setError()
setError ($msg) protected
Add an error message to the error container.
Parameters
string $msg
Referenced by PHPMailer\addAnAddress(), PHPMailer\addAttachment(), PHPMailer\addEmbeddedImage(), PHPMailer\addOrEnqueueAnAddress(), PHPMailer\addStringAttachment(), PHPMailer\addStringEmbeddedImage(), PHPMailer\encodeFile(), PHPMailer\encodeString(), PHPMailer\set(), and PHPMailer\smtpSend().
setFrom()
setFrom ($address, $name = '', $auto = true)
Set the From and FromName properties.
Parameters
string $address
string $name
bool $auto Whether to also set the Sender address, defaults to true
Exceptions
Exception
Returns
bool
setLanguage()
setLanguage ($langcode = 'en', $lang_path = '')
Set the language for error messages. The default language is English.
Parameters
string $langcode ISO 639-1 2-character language code (e.g. French is "fr") Optionally, the language code can be enhanced with a 4-character script annotation and/or a 2-character country annotation.
string $lang_path Path to the language file directory, with trailing separator (slash) Do not set this from user input!
Returns
bool Returns true if the requested language was loaded, false otherwise.
Referenced by PHPMailer\getTranslations(), and PHPMailer\lang().
setLE()
static setLE ($le) static protected
Set the line break format string, e.g. "\r\n".
Parameters
string $le
setMessageType()
setMessageType () protected
Set the message type. PHPMailer only supports some preset message types, not arbitrary MIME structures.
setOAuth()
setOAuth (OAuthTokenProvider $oauth)
Set an OAuthTokenProvider instance.
setSMTPInstance()
setSMTPInstance (SMTP $smtp)
Provide an instance to use for SMTP operations.
Returns
SMTP
setWordWrap()
setWordWrap ()
Apply word wrapping to the message body. Wraps the message body to the number of chars set in the WordWrap property. You should only do this to plain-text bodies as wrapping HTML tags may break them. This is called automatically by createBody(), so you don't need to call it yourself.
Referenced by PHPMailer\createBody().
sign()
sign ($cert_filename, $key_filename, $key_pass, $extracerts_filename = '')
Set the public and private key files and password for S/MIME signing.
Parameters
string $cert_filename
string $key_filename
string $key_pass Password for private key
string $extracerts_filename Optional path to chain certificate
smtpClose()
smtpClose ()
Close the active SMTP session if one exists.
Referenced by PHPMailer\__destruct().
smtpConnect()
smtpConnect ($options = null)
Initiate a connection to an SMTP server. Returns false if the operation failed.
Parameters
array $options An array of options compatible with stream_context_create()
Exceptions
Exception
@uses \PHPMailer\PHPMailer\SMTP
Returns
bool
Referenced by PHPMailer\smtpSend().
smtpSend()
smtpSend ($header, $body) protected
Send mail via SMTP. Returns false if there is a bad MAIL FROM, RCPT, or DATA input.
See also
PHPMailer::setSMTPInstance() to use a different class.
@uses \PHPMailer\PHPMailer\SMTP
Parameters
string $header The message headers
string $body The message body
Exceptions
Exception
Returns
bool
stripTrailingBreaks()
static stripTrailingBreaks ($text) static
Strip trailing line breaks from a string.
Parameters
string $text
Returns
string The text to remove breaks from
stripTrailingWSP()
static stripTrailingWSP ($text) static
Remove trailing whitespace from a string.
Parameters
string $text
Returns
string The text to remove whitespace from
textLine()
textLine ($value)
Return a formatted mail line.
Parameters
string $value
Returns
string
Referenced by PHPMailer\createBody(), PHPMailer\getBoundary(), and PHPMailer\getMailMIME().
utf8CharBoundary()
utf8CharBoundary ($encodedText, $maxLength)
Find the last character boundary prior to $maxLength in a utf-8 quoted-printable encoded string. Original written by Colin Brown.
Parameters
string $encodedText utf-8 QP text
int $maxLength Find the last character boundary prior to this length
Returns
int
Referenced by PHPMailer\wrapText().
validateAddress()
static validateAddress ($address, $patternselect = null) static
Check that a string looks like an email address. Validation patterns supported:
auto Pick best pattern automatically;
pcre8 Use the squiloople.com pattern, requires PCRE > 8.0;
pcre Use old PCRE implementation;
php Use PHP built-in FILTER_VALIDATE_EMAIL;
html5 Use the pattern given by the HTML5 spec for 'email' type form input elements.
noregex Don't use a regex: super fast, really dumb. Alternatively you may pass in a callable to inject your own validator, for example:
PHPMailer::validateAddress('user@example.com', function($address) {
    return (strpos($address, '@') !== false);
});
You can also set the PHPMailer::$validator static to a callable, allowing built-in methods to use your validator.
Parameters
string $address The email address to check
string | callable $patternselect Which pattern to use
Returns
bool
validateEncoding()
validateEncoding ($encoding) protected
Validate encodings.
Parameters
string $encoding
Returns
bool
Referenced by PHPMailer\addAttachment(), PHPMailer\addEmbeddedImage(), PHPMailer\addStringAttachment(), and PHPMailer\addStringEmbeddedImage().
wrapText()
wrapText ($message, $length, $qp_mode = false)
Word-wrap message. For use with mailers that do not automatically perform wrapping and for quoted-printable encoded messages. Original written by philippe.
Parameters
string $message The message to wrap
int $length The line length to wrap to
bool $qp_mode Whether to run in Quoted-Printable mode
Returns
string
Referenced by PHPMailer\encodeHeader(), and PHPMailer\setWordWrap().
Member Data Documentation
$dsn
$dsn = ''
Comma separated list of DSN notifications 'NEVER' under no circumstances a DSN must be returned to the sender. If you use NEVER all other notifications will be ignored. 'SUCCESS' will notify you when your mail has arrived at its destination. 'FAILURE' will arrive if an error occurred during delivery. 'DELAY' will notify you if there is an unusual delay in delivery, but the actual delivery's outcome (success or failure) is not yet decided.
See also
https://tools.ietf.org/html/rfc3461 See section 4.1 for more information about NOTIFY
$IcalMethods
$IcalMethods static protected
Initial value:
= [
        self::ICAL_METHOD_REQUEST,
        self::ICAL_METHOD_PUBLISH,
        self::ICAL_METHOD_REPLY,
        self::ICAL_METHOD_ADD,
        self::ICAL_METHOD_CANCEL,
        self::ICAL_METHOD_REFRESH,
        self::ICAL_METHOD_COUNTER,
        self::ICAL_METHOD_DECLINECOUNTER,
    ]
CRLF
const CRLF = "\r\n"
The SMTP standard CRLF line break. If you want to change line break format, change static::$LE, not this.
Referenced by PHPMailer\DKIM_BodyC().
FWS
const FWS = ' '
"Folding White Space" a white space string used for line folding.
The documentation for this class was generated from the following file:
/var/www/html/utopszkij_fw/vendor/phpmailer/src/PHPMailer.php