Utopszkij_fw: PHPGangsta_GoogleAuthenticator Class Reference
PHPGangsta_GoogleAuthenticator Class Reference
Public Member Functions
createSecret ($secretLength=16)
getCode ($secret, $timeSlice=null)
getQRCodeGoogleUrl ($name, $secret, $title=null, $params=array())
verifyCode ($secret, $code, $discrepancy=1, $currentTimeSlice=null)
setCodeLength ($length)
Protected Member Functions
_base32Decode ($secret)
_getBase32LookupTable ()
Protected Attributes
$_codeLength = 6
Detailed Description
PHP Class for handling Google Authenticator 2-factor authentication.
Author
Michael Kliewe
Copyright
2012 Michael Kliewe @license http://www.opensource.org/licenses/bsd-license.php BSD License
http://www.phpgangsta.de/
Member Function Documentation
_base32Decode()
_base32Decode ($secret) protected
Helper class to decode base32.
Parameters
$secret
Returns
bool|string
Referenced by getCode().
_getBase32LookupTable()
_getBase32LookupTable () protected
Get array with all 32 characters for decoding from/encoding to base32.
Returns
array
Referenced by _base32Decode(), and createSecret().
createSecret()
createSecret ($secretLength = 16)
Create new secret. 16 characters, randomly chosen from the allowed base32 characters.
Parameters
int $secretLength
Returns
string
getCode()
getCode ($secret, $timeSlice = null)
Calculate the code, with given secret and point in time.
Parameters
string $secret
int | null $timeSlice
Returns
string
Referenced by verifyCode().
getQRCodeGoogleUrl()
getQRCodeGoogleUrl ($name, $secret, $title = null, $params = array())
Get QR-Code URL for image, from google charts.
Parameters
string $name
string $secret
string $title
array $params
Returns
string
setCodeLength()
setCodeLength ($length)
Set the code length, should be >=6.
Parameters
int $length
Returns
PHPGangsta_GoogleAuthenticator
verifyCode()
verifyCode ($secret, $code, $discrepancy = 1, $currentTimeSlice = null)
Check if the code is correct. This will accept codes starting from $discrepancy*30sec ago to $discrepancy*30sec from now.
Parameters
string $secret
string $code
int $discrepancy This is the allowed time drift in 30 second units (8 means 4 minutes before or after)
int | null $currentTimeSlice time slice if we want use other that time()
Returns
bool
The documentation for this class was generated from the following file:
/var/www/html/utopszkij_fw/vendor/PHPGangsta/GoogleAuthenticator.php