Utopszkij_fw: POP3 Class Reference
POP3 Class Reference
Public Member Functions
authorise ($host, $port=false, $timeout=false, $username='', $password='', $debug_level=0)
connect ($host, $port=false, $tval=30)
login ($username='', $password='')
disconnect ()
getErrors ()
Static Public Member Functions
static popBeforeSmtp ($host, $port=false, $timeout=false, $username='', $password='', $debug_level=0)
Public Attributes
const VERSION = '6.7.1'
const DEFAULT_PORT = 110
const DEFAULT_TIMEOUT = 30
$do_debug = self::DEBUG_OFF
$host
$port
$tval
$username
$password
const LE = "\r\n"
const DEBUG_OFF = 0
const DEBUG_SERVER = 1
const DEBUG_CLIENT = 2
Protected Member Functions
getResponse ($size=128)
sendString ($string)
checkResponse ($string)
setError ($error)
catchWarning ($errno, $errstr, $errfile, $errline)
Protected Attributes
$pop_conn
$connected = false
$errors = []
Detailed Description
PHPMailer POP-Before-SMTP Authentication Class. Specifically for PHPMailer to use for RFC1939 POP-before-SMTP authentication. 1) This class does not support APOP authentication. 2) Opening and closing lots of POP3 connections can be quite slow. If you need to send a batch of emails then just perform the authentication once at the start, and then loop through your mail sending script. Providing this process doesn't take longer than the verification period lasts on your POP3 server, you should be fine. 3) This is really ancient technology; you should only need to use it to talk to very old systems. 4) This POP3 class is deliberately lightweight and incomplete, implementing just enough to do authentication. If you want a more complete class there are other POP3 classes for PHP available.
Author
Richard Davey (original author) rich@.nosp@m.core.nosp@m.php.c.nosp@m.o.uk
Marcus Bointon (Synchro/coolbru) phpma.nosp@m.iler.nosp@m.@sync.nosp@m.hrom.nosp@m.edia..nosp@m.co.u.nosp@m.k
Jim Jagielski (jimjag) jimja.nosp@m.g@gm.nosp@m.ail.c.nosp@m.om
Andy Prevost (codeworxtech) codew.nosp@m.orxt.nosp@m.ech@u.nosp@m.sers.nosp@m..sour.nosp@m.cefo.nosp@m.rge.n.nosp@m.et
Member Function Documentation
authorise()
authorise ($host, $port = false, $timeout = false, $username = '', $password = '', $debug_level = 0)
Authenticate with a POP3 server. A connect, login, disconnect sequence appropriate for POP-before SMTP authorisation.
Parameters
string $host The hostname to connect to
int | bool $port The port number to connect to
int | bool $timeout The timeout value
string $username
string $password
int $debug_level
Returns
bool
catchWarning()
catchWarning ($errno, $errstr, $errfile, $errline) protected
POP3 connection error handler.
Parameters
int $errno
string $errstr
string $errfile
int $errline
checkResponse()
checkResponse ($string) protected
Checks the POP3 server response. Looks for for +OK or -ERR.
Parameters
string $string
Returns
bool
Referenced by POP3\connect(), and POP3\login().
connect()
connect ($host, $port = false, $tval = 30)
Connect to a POP3 server.
Parameters
string $host
int | bool $port
int $tval
Returns
bool
Referenced by POP3\authorise().
disconnect()
disconnect ()
Disconnect from the POP3 server.
Referenced by POP3\authorise().
getErrors()
getErrors ()
Get an array of error messages, if any.
Returns
array
getResponse()
getResponse ($size = 128) protected
Get a response from the POP3 server.
Parameters
int $size The maximum number of bytes to retrieve
Returns
string
Referenced by POP3\connect(), POP3\disconnect(), and POP3\login().
login()
login ($username = '', $password = '')
Log in to the POP3 server. Does not support APOP (RFC 2828, 4949).
Parameters
string $username
string $password
Returns
bool
Referenced by POP3\authorise().
popBeforeSmtp()
static popBeforeSmtp ($host, $port = false, $timeout = false, $username = '', $password = '', $debug_level = 0) static
Simple static wrapper for all-in-one POP before SMTP.
Parameters
string $host The hostname to connect to
int | bool $port The port number to connect to
int | bool $timeout The timeout value
string $username
string $password
int $debug_level
Returns
bool
sendString()
sendString ($string) protected
Send raw data to the POP3 server.
Parameters
string $string
Returns
int
Referenced by POP3\disconnect(), and POP3\login().
setError()
setError ($error) protected
Add an error to the internal error store. Also display debug output if it's enabled.
Parameters
string $error
Referenced by POP3\catchWarning(), POP3\checkResponse(), POP3\connect(), and POP3\login().
Member Data Documentation
LE
const LE = "\r\n"
Line break constant.
The documentation for this class was generated from the following file:
/var/www/html/utopszkij_fw/vendor/phpmailer/src/POP3.php