Utopszkij_fw: SMTP Class Reference
SMTP Class Reference
Public Member Functions
connect ($host, $port=null, $timeout=30, $options=[])
startTLS ()
authenticate ($username, $password, $authtype=null, $OAuth=null)
connected ()
close ()
data ($msg_data)
hello ($host='')
mail ($from)
quit ($close_on_error=true)
recipient ($address, $dsn='')
reset ()
sendAndMail ($from)
verify ($name)
noop ()
turn ()
client_send ($data, $command='')
getError ()
getServerExtList ()
getServerExt ($name)
getLastReply ()
setVerp ($enabled=false)
getVerp ()
setDebugOutput ($method='echo')
getDebugOutput ()
setDebugLevel ($level=0)
getDebugLevel ()
setTimeout ($timeout=0)
getTimeout ()
getLastTransactionID ()
Public Attributes
const VERSION = '6.7.1'
const LE = "\r\n"
const DEFAULT_PORT = 25
const MAX_LINE_LENGTH = 998
const MAX_REPLY_LENGTH = 512
const DEBUG_OFF = 0
const DEBUG_CLIENT = 1
const DEBUG_SERVER = 2
const DEBUG_CONNECTION = 3
const DEBUG_LOWLEVEL = 4
$do_debug = self::DEBUG_OFF
$Debugoutput = 'echo'
$do_verp = false
$Timeout = 300
$Timelimit = 300
Protected Member Functions
edebug ($str, $level=0)
getSMTPConnection ($host, $port=null, $timeout=30, $options=[])
hmac ($data, $key)
sendHello ($hello, $host)
parseHelloFields ($type)
sendCommand ($command, $commandstring, $expect)
get_lines ()
setError ($message, $detail='', $smtp_code='', $smtp_code_ex='')
errorHandler ($errno, $errmsg, $errfile='', $errline=0)
recordLastTransactionID ()
Protected Attributes
$smtp_transaction_id_patterns
$helo_rply
$server_caps
$last_reply = ''
Detailed Description
PHPMailer RFC821 SMTP email transport class. Implements RFC 821 SMTP commands and provides some utility methods for sending mail to an SMTP server.
Author
Chris Ryan
Marcus Bointon phpma.nosp@m.iler.nosp@m.@sync.nosp@m.hrom.nosp@m.edia..nosp@m.co.u.nosp@m.k
Member Function Documentation
authenticate()
authenticate ($username, $password, $authtype = null, $OAuth = null)
Perform SMTP authentication. Must be run after hello().
See also
hello()
Parameters
string $username The user name
string $password The password
string $authtype The auth type (CRAM-MD5, PLAIN, LOGIN, XOAUTH2)
OAuthTokenProvider $OAuth An optional OAuthTokenProvider instance for XOAUTH2 authentication
Returns
bool True if successfully authenticated
client_send()
client_send ($data, $command = '')
Send raw data to the server.
Parameters
string $data The data to send
string $command Optionally, the command this is part of, used only for controlling debug output
Returns
int|bool The number of bytes sent to the server or false on error
Referenced by SMTP\data(), and SMTP\sendCommand().
close()
close ()
Close the socket and clean up the state of the class. Don't use this function without first trying to use QUIT.
See also
quit()
Referenced by SMTP\connect(), SMTP\connected(), and SMTP\quit().
connect()
connect ($host, $port = null, $timeout = 30, $options = [])
Connect to an SMTP server.
Parameters
string $host SMTP server IP or host name
int $port The port number to connect to
int $timeout How long to wait for the connection to open
array $options An array of options for stream_context_create()
Returns
bool
connected()
connected ()
Check connection state.
Returns
bool True if connected
Referenced by SMTP\connect(), and SMTP\sendCommand().
data()
data ($msg_data)
Send an SMTP DATA command. Issues a data command and sends the msg_data to the server, finalizing the mail transaction. $msg_data is the message that is to be send with the headers. Each header needs to be on a single line followed by a <CRLF> with the message headers and the message body being separated by an additional <CRLF>. Implements RFC 821: DATA <CRLF>.
Parameters
string $msg_data Message data to send
Returns
bool
edebug()
edebug ($str, $level = 0) protected
Output debugging info via a user-selected method.
Parameters
string $str Debug string to output
int $level The debug level of this message; see DEBUG_* constants
See also
SMTP::$Debugoutput
SMTP::$do_debug
Referenced by SMTP\authenticate(), SMTP\client_send(), SMTP\close(), SMTP\connect(), SMTP\connected(), SMTP\errorHandler(), SMTP\get_lines(), SMTP\getSMTPConnection(), SMTP\sendCommand(), and SMTP\turn().
errorHandler()
errorHandler ($errno, $errmsg, $errfile = '', $errline = 0) protected
Reports an error number and string.
Parameters
int $errno The error number returned by PHP
string $errmsg The error message returned by PHP
string $errfile The file the error occurred in
int $errline The line number the error occurred on
get_lines()
get_lines () protected
Read the SMTP server's response. Either before eof or socket timeout occurs on the operation. With SMTP we can tell if we have more lines to read if the 4th character is '-' symbol. If it is a space then we don't need to read anything else.
Returns
string
Referenced by SMTP\connect(), and SMTP\sendCommand().
getDebugLevel()
getDebugLevel ()
Get debug output level.
Returns
int
getDebugOutput()
getDebugOutput ()
Get debug output method.
Returns
string
getError()
getError ()
Get the latest error.
Returns
array
Referenced by SMTP\get_lines().
getLastReply()
getLastReply ()
Get the last reply from the server.
Returns
string
Referenced by SMTP\recordLastTransactionID().
getLastTransactionID()
getLastTransactionID ()
Get the queue/transaction ID of the last SMTP transaction If no reply has been received yet, it will return null. If no pattern was matched, it will return false.
Returns
bool|string|null
See also
recordLastTransactionID()
getServerExt()
getServerExt ($name)
Get metadata about the SMTP server from its HELO/EHLO response. The method works in three ways, dependent on argument value and current state:
HELO/EHLO has not been sent - returns null and populates $this->error.
HELO has been sent - $name == 'HELO': returns server name $name == 'EHLO': returns boolean false $name == any other string: returns null and populates $this->error
EHLO has been sent - $name == 'HELO'|'EHLO': returns the server name $name == any other string: if extension $name exists, returns True or its options (e.g. AUTH mechanisms supported). Otherwise returns False.
Parameters
string $name Name of SMTP extension or 'HELO'|'EHLO'
Returns
string|bool|null
getServerExtList()
getServerExtList ()
Get SMTP extensions available on the server.
Returns
array|null
getSMTPConnection()
getSMTPConnection ($host, $port = null, $timeout = 30, $options = []) protected
Create connection to the SMTP server.
Parameters
string $host SMTP server IP or host name
int $port The port number to connect to
int $timeout How long to wait for the connection to open
array $options An array of options for stream_context_create()
Returns
false|resource
Referenced by SMTP\connect().
getTimeout()
getTimeout ()
Get SMTP timeout.
Returns
int
getVerp()
getVerp ()
Get VERP address generation mode.
Returns
bool
hello()
hello ($host = '')
Send an SMTP HELO or EHLO command. Used to identify the sending server to the receiving server. This makes sure that client and server are in a known state. Implements RFC 821: HELO <SP> <domain> <CRLF> and RFC 2821 EHLO.
Parameters
string $host The host name or IP to connect to
Returns
bool
hmac()
hmac ($data, $key) protected
Calculate an MD5 HMAC hash. Works like hash_hmac('md5', $data, $key) in case that function is not available.
Parameters
string $data The data to hash
string $key The key to hash with
Returns
string
Referenced by SMTP\authenticate().
mail()
mail ($from)
Send an SMTP MAIL command. Starts a mail transaction from the email address specified in $from. Returns true if successful or false otherwise. If True the mail transaction is started and then one or more recipient commands may be called followed by a data command. Implements RFC 821: MAIL <SP> FROM:<reverse-path> <CRLF>.
Parameters
string $from Source address of this message
Returns
bool
noop()
noop ()
Send an SMTP NOOP command. Used to keep keep-alives alive, doesn't actually do anything.
Returns
bool
parseHelloFields()
parseHelloFields ($type) protected
Parse a reply to HELO/EHLO command to discover server extensions. In case of HELO, the only parameter that can be discovered is a server name.
Parameters
string $type HELO or EHLO
Referenced by SMTP\sendHello().
quit()
quit ($close_on_error = true)
Send an SMTP QUIT command. Closes the socket if there is no error or the $close_on_error argument is true. Implements from RFC 821: QUIT <CRLF>.
Parameters
bool $close_on_error Should the connection close if an error occurs?
Returns
bool
Referenced by SMTP\connect().
recipient()
recipient ($address, $dsn = '')
Send an SMTP RCPT command. Sets the TO argument to $toaddr. Returns true if the recipient was accepted false if it was rejected. Implements from RFC 821: RCPT <SP> TO:<forward-path> <CRLF>.
Parameters
string $address The address the message is being sent to
string $dsn Comma separated list of DSN notifications. NEVER, SUCCESS, FAILURE or DELAY. If you specify NEVER all other notifications are ignored.
Returns
bool
recordLastTransactionID()
recordLastTransactionID () protected
Extract and return the ID of the last SMTP transaction based on a list of patterns provided in SMTP::$smtp_transaction_id_patterns. Relies on the host providing the ID in response to a DATA command. If no reply has been received yet, it will return null. If no pattern was matched, it will return false.
Returns
bool|string|null
Referenced by SMTP\data().
reset()
reset ()
Send an SMTP RSET command. Abort any transaction that is currently in progress. Implements RFC 821: RSET <CRLF>.
Returns
bool True on success
sendAndMail()
sendAndMail ($from)
Send an SMTP SAML command. Starts a mail transaction from the email address specified in $from. Returns true if successful or false otherwise. If True the mail transaction is started and then one or more recipient commands may be called followed by a data command. This command will send the message to the users terminal if they are logged in and send them an email. Implements RFC 821: SAML <SP> FROM:<reverse-path> <CRLF>.
Parameters
string $from The address the message is from
Returns
bool
sendCommand()
sendCommand ($command, $commandstring, $expect) protected
Send a command to an SMTP server and check its return code.
Parameters
string $command The command name - not sent to the server
string $commandstring The actual command to send
int | array $expect One or more expected integer success codes
Returns
bool True on success
Referenced by SMTP\authenticate(), SMTP\data(), SMTP\mail(), SMTP\noop(), SMTP\quit(), SMTP\recipient(), SMTP\reset(), SMTP\sendAndMail(), SMTP\sendHello(), SMTP\startTLS(), and SMTP\verify().
sendHello()
sendHello ($hello, $host) protected
Send an SMTP HELO or EHLO command. Low-level implementation used by hello().
Parameters
string $hello The HELO string
string $host The hostname to say we are
Returns
bool
See also
hello()
Referenced by SMTP\hello().
setDebugLevel()
setDebugLevel ($level = 0)
Set debug output level.
Parameters
int $level
setDebugOutput()
setDebugOutput ($method = 'echo')
Set debug output method.
Parameters
string | callable $method The name of the mechanism to use for debugging output, or a callable to handle it
setError()
setError ($message, $detail = '', $smtp_code = '', $smtp_code_ex = '') protected
Set error messages and codes.
Parameters
string $message The error message
string $detail Further detail on the error
string $smtp_code An associated SMTP error code
string $smtp_code_ex Extended SMTP code
Referenced by SMTP\authenticate(), SMTP\connect(), SMTP\errorHandler(), SMTP\get_lines(), SMTP\getServerExt(), SMTP\getSMTPConnection(), SMTP\sendCommand(), and SMTP\turn().
setTimeout()
setTimeout ($timeout = 0)
Set SMTP timeout.
Parameters
int $timeout The timeout duration in seconds
setVerp()
setVerp ($enabled = false)
Enable or disable VERP address generation.
Parameters
bool $enabled
startTLS()
startTLS ()
Initiate a TLS (encrypted) session.
Returns
bool
turn()
turn ()
Send an SMTP TURN command. This is an optional command for SMTP that this class does not support. This method is here to make the RFC821 Definition complete for this class and may be implemented in future. Implements from RFC 821: TURN <CRLF>.
Returns
bool
verify()
verify ($name)
Send an SMTP VRFY command.
Parameters
string $name The name to verify
Returns
bool
The documentation for this class was generated from the following file:
/var/www/html/utopszkij_fw/vendor/phpmailer/src/SMTP.php